### ISSUE TITLE
Calculating closest character

### ISSUE THREAD

**Issue by sweetgriff1056** [lokisapocalypse/wowstuff#1]
Unsure if this is an issue because I've missed something but the "calculating closest character" function doesn't appear to be working (I have tried multiple browsers).

I attempted to add all of my characters via the Change Character tab on the sidebar but this doesn't seem to change anything.

If possible please can you get back to me on this as this is a feature I had purchased premium for, thanks in advance :)

**Comment by lokisapocalypse** [comment]
Thanks for bringing this up, I'll take a look at it this week and get back to you.

**Comment by lokisapocalypse** [comment]
This issue should be fixed now. Please let me know if you encounter any further issues.

**Comment by sweetgriff1056** [comment]
There's now the option for me to sync characters however it's only connecting to my US Edition of WoW and linking those characters but I haven't actively played those as I am primarily EU. Is it possible to amend to show my EU characters?

I haven't seen anything in the options and when I tried syncing to BNet again.

Many thanks for the quick responses!

**Comment by lokisapocalypse** [comment]
Oh that's an interesting point. I hadn't considered looking cross realm for character. It probably wouldn't be too difficult to search across all realms. I'll take a look at that.

**Comment by lokisapocalypse** [comment]
So here's the problem. I can't just spam all the regions because you need to authorize your account for each region. I'll need to think about a better long term solution but in the short term, if you want to message me your EU toons, I can manually add them.

**Comment by Tgarvar** [comment]
I think that calculating closest character is broken again. I purchased premium for it, but it does not seem to be loading.

**Comment by lokisapocalypse** [comment]
I'll take a look at it this weekend. If you send me your email, I'll refund your most recent premium purchase.

**Comment by lokisapocalypse** [comment]
I fixed it. It was a server error with the api. Should be working now but please reach out if you find anything else broken.
