### ISSUE TITLE
Unsubcribe and still being charged

### ISSUE THREAD

**Issue by ghost** [lokisapocalypse/wowstuff#2]
Hi 

I want to unsubscribe to wow-rep.com and there is no option to do it.

**Comment by lokisapocalypse** [comment]
Hello! If you are signed in on the site, in the top right corner should be the image of a person. If you hover over it, one of the links should be Cancel Premium. 

If you still run in to trouble, let me know what your email address is and I can cancel it manually.

**Comment by ghost** [comment]
There is no unsub button. I know I will get a message back saying I am not subscribed however I have attached proof 

![Screenshot 2022-09-08 201547](https://user-images.githubusercontent.com/113126619/189247205-032e1f97-a35f-49a8-9ba0-5c916aa8b567.jpg)
![Screenshot 2022-09-08 201708](https://user-images.githubusercontent.com/113126619/189247295-6bb0cb76-bf0b-42ca-b9a4-89af0af0b6a1.jpg)

**Comment by lokisapocalypse** [comment]
That's weird. What is your email address? I can manually do it but I need the email address you signed up with.

**Comment by ghost** [comment]
Lyrette.denis@gmail.com

**Comment by lokisapocalypse** [comment]
In looking at your account, it looks like you'd already unsubscribed. In checking my payment processor, it looks like you were charged one time and I have refunded that. Please let me know if there's anything else you need.

**Comment by ghost** [comment]
![Screenshot 2022-11-09 133023](https://user-images.githubusercontent.com/113126619/200912056-731f96dd-2d2a-4bd7-aa51-a58447132610.jpg)
 
I was charged again. Shall I request a charge back with my credit card company ?

**Comment by lokisapocalypse** [comment]
That's...weird. I'm not sure why you were charged again but I've refunded the charge. Please let me know if it happens again.

**Comment by ghost** [comment]
I was charged again. 

Please delete my account on https://wow-rep.com/ 

![image](https://user-images.githubusercontent.com/113126619/206479908-bff72f77-65d7-4157-abce-a7a2213d969d.png)
![image](https://user-images.githubusercontent.com/113126619/206480240-051fab0b-04ba-4f4c-8821-bce9d797cfb6.png)

**Comment by lokisapocalypse** [comment]
I have refunded you again and deleted you from the users table. I apologize
that this keeps happening but hopefully this will resolve the issue.

Thanks,

Brian Lamb
