### ISSUE TITLE
Closest Character Not Populating

### ISSUE THREAD

**Issue by gallypsa** [lokisapocalypse/wowstuff#3]
Closest character doesn't seem to be populating.  I've logged into different characters on EU Draenor and it doesn't not populate.

**Comment by lokisapocalypse** [comment]
I wonder if it's an issue specifically with EU. Can you provide me the character you are trying with and I can try to replicate on my end?

**Comment by gallypsa** [comment]
Thanks for looking into this.  Here are a few of my characters:

Florecitas
Samhaina
Galleleah
Kallypsa

All of them are in EU Draenor.

**Comment by lokisapocalypse** [comment]
I looked in to it a little this afternoon and it looks like the link to sync characters has disappeared. I'll need to implement a fix for that but for now, I've manually added these for you. If there are any others you'd like to have added, please let me know.

**Comment by lokisapocalypse** [comment]
Looks like it got disabled by mistake. You should find a link under the user menu once you are logged in. Please let me know if that doesn't work for you.
