### ISSUE TITLE
Unable to reset password.

### ISSUE THREAD

**Issue by SparkledMoon** [lokisapocalypse/wowstuff#5]
Whenever I request to reset my password, it says that is unable to send the email. (intotheabyss@live.com)

**Comment by lokisapocalypse** [comment]
Yeah there seems to be some issue with the email server. I'm taking a look at it today and will let you know when it's resolved.

**Comment by SparkledMoon** [comment]
Still not able to reset my password to use the service I am paying for...

**Comment by lokisapocalypse** [comment]
Sorry for the inconvenience. I've manually sent the password reset email. Google changed how third parties use their apis to send emails and I haven't had the time to dedicate to replacing all that code. In the meantime, just let me know if you need another reset and I can manually do it for you.

**Comment by SparkledMoon** [comment]
Thank you very much!
