### ISSUE TITLE
Premium unsubscribe not working

### ISSUE THREAD

**Issue by cptlemons** [lokisapocalypse/wowstuff#8]
It looks like the premium unsubscribe does not process through the entire system as I am still being charged. This appears to be a recurring issues ([1](https://github.com/lokisapocalypse/wowstuff/issues/2), [2](https://github.com/lokisapocalypse/wowstuff/issues/6)), so please delete my account manually as well. My account email is mkoler@gmail.com.

Suggest adding self service account deletion or disabling the premium functionality and subscriptions.

**Comment by lokisapocalypse** [comment]
Sorry about that! I haven't had as much time to work on the site as I'd like. I've cancelled your subscription, deleted you from the database, and refunded your most recent charge. If there is anything else I can do to help, please let me know.
